version: '2.1'

services:
  db-service:
    image: mysql:5.7
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=dronedb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    container_name: mysql-database
