spring:
  application:
    name: drones
  h2:
    console:
      enabled: true
      path: /db
  datasource:
    username: user
    password: password
    url: jdbc:mysql://localhost:3308/dronedb
    driver-class-name: com.mysql.cj.jdbc.Driver
    maximum-pool-size: 10
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
